/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaraunt;

import java.util.ArrayList;

/**
 *
 * @author tejgi_000
 */
public class CookUI extends javax.swing.JFrame {

    private RestaurantController controller;
    private CookOrderQueueScreen orderQueueScreen;
    private CookOrderDetailsScreen orderDetailsScreen;
    
    /**
     * Creates new form CookUI
     */
    public CookUI(RestaurantController controller) {
        //initComponents();
        orderQueueScreen = new CookOrderQueueScreen(new ArrayList<Order>(), this);
        orderDetailsScreen = new CookOrderDetailsScreen(new Order(0,0), this);
        this.controller = controller;
        setContentPane(orderQueueScreen);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCookHome = new javax.swing.JPanel();

        javax.swing.GroupLayout panelCookHomeLayout = new javax.swing.GroupLayout(panelCookHome);
        panelCookHome.setLayout(panelCookHomeLayout);
        panelCookHomeLayout.setHorizontalGroup(
            panelCookHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        panelCookHomeLayout.setVerticalGroup(
            panelCookHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCookHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCookHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCookHome;
    // End of variables declaration//GEN-END:variables

    public void showOrderQueueScreen() {
        setContentPane(orderQueueScreen);
        pack();
    }

    public void showOrderDetailsScreen() {
        setContentPane(orderDetailsScreen);
        pack();
    }
}
