/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaraunt;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author dmhaffner
 */
public class CookOrderQueueScreen extends javax.swing.JPanel {

    private CookUI cookUI;
    
    /**
     * Creates new form CookOrderQueueScreen
     */
    public CookOrderQueueScreen(ArrayList<Order> orders, CookUI cookUI) {
        this.cookUI = cookUI;
        initComponents();
        initOrderQueue(orders);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderQueueScrollPane = new javax.swing.JScrollPane();
        listOrderQueue = new javax.swing.JList();
        orderQueueLabel = new javax.swing.JLabel();
        btnOrderDetails = new javax.swing.JButton();

        listOrderQueue.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        orderQueueScrollPane.setViewportView(listOrderQueue);

        orderQueueLabel.setText("Order Queue");

        btnOrderDetails.setText("Order Details");
        btnOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderQueueScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderQueueLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(btnOrderDetails)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orderQueueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderQueueScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderDetails)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailsActionPerformed
        
        Order temp = (Order)listOrderQueue.getSelectedValue();
        cookUI.showOrderDetailsScreen(temp);
    }//GEN-LAST:event_btnOrderDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderDetails;
    private javax.swing.JList listOrderQueue;
    private javax.swing.JLabel orderQueueLabel;
    private javax.swing.JScrollPane orderQueueScrollPane;
    // End of variables declaration//GEN-END:variables

    private void initOrderQueue(ArrayList<Order> orders) {
        javax.swing.DefaultListModel<String> listModel;
        listModel = new javax.swing.DefaultListModel<>();
        
        //listModel.addElement("test 1");
        //listModel.addElement("test 2");
        //listModel.addElement("test 3");
        
        for (Order order : orders) {
            listModel.addElement(order.toString());
        }
        listOrderQueue.setModel(listModel);
    }
    
    public void populateOrderQueueScreen(){
        
        DefaultListModel<Order> listModel;
        listModel = new DefaultListModel<Order>();
        
        ArrayList<Order> temp = cookUI.getOrderList();
        
        for(int i =0; i < temp.size();i++){
            listModel.addElement(temp.get(i));
        }
        
        listOrderQueue.setModel(listModel);
    }
}
