/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaraunt;

import java.util.ArrayList;

/**
 *
 * @author tejgi_000
 */
public class WaiterAddItemScreen extends javax.swing.JPanel {
    
    private WaiterUI waiterUI;
    /**
     * Creates new form WaiterAddItemScreen
     */
    public WaiterAddItemScreen(WaiterUI waiterUI) {
        this.waiterUI = waiterUI;
        initComponents();
        initCategories();
        initItems();
        initQuantities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddItemTitle = new javax.swing.JLabel();
        lblPromptCategory = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox();
        lblpromptItem = new javax.swing.JLabel();
        cbItem = new javax.swing.JComboBox();
        btnAddItem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbQuantity = new javax.swing.JComboBox();
        lblPromptQuantity = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSubtotalValue = new javax.swing.JLabel();

        lblAddItemTitle.setText("Add an Item to Order");

        lblPromptCategory.setText("Choose Category");

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCategoryItemStateChanged(evt);
            }
        });
        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });

        lblpromptItem.setText("Choose Item");

        cbItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemItemStateChanged(evt);
            }
        });
        cbItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItemActionPerformed(evt);
            }
        });

        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbQuantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbQuantityMouseClicked(evt);
            }
        });
        cbQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuantityActionPerformed(evt);
            }
        });

        lblPromptQuantity.setText("Choose Quantity");

        jLabel3.setText("Subtotal:");

        lblSubtotalValue.setText("$0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSubtotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromptCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddItemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpromptItem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbItem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromptQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddItemTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPromptCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpromptItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPromptQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSubtotalValue))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        String name = cbItem.getSelectedItem().toString();
        String category = cbCategory.getSelectedItem().toString();
        int quantity = cbQuantity.getSelectedIndex()+1;
        
        System.out.println(""+quantity+" of "+ name +" from "+ category);
        waiterUI.addItemToOrder(name,category,quantity);
        //waiterUI.AddItem();
        waiterUI.showCurrentTableScreen();
        
        
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        waiterUI.showCurrentTableScreen();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
        //initItems();
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void cbItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItemActionPerformed
        // TODO add your handling code here:
        updateSubtotal();
    }//GEN-LAST:event_cbItemActionPerformed

    private void cbQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuantityActionPerformed
        // TODO add your handling code here:
        updateSubtotal();
    }//GEN-LAST:event_cbQuantityActionPerformed

    private void cbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCategoryItemStateChanged
        // TODO add your handling code here:
        initItems();
    }//GEN-LAST:event_cbCategoryItemStateChanged

    private void cbItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemItemStateChanged
        // TODO add your handling code here:
        //updateSubtotal();
    }//GEN-LAST:event_cbItemItemStateChanged

    private void cbQuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbQuantityMouseClicked
        // TODO add your handling code here:
        //updateSubtotal();
    }//GEN-LAST:event_cbQuantityMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cbCategory;
    private javax.swing.JComboBox cbItem;
    private javax.swing.JComboBox cbQuantity;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddItemTitle;
    private javax.swing.JLabel lblPromptCategory;
    private javax.swing.JLabel lblPromptQuantity;
    private javax.swing.JLabel lblSubtotalValue;
    private javax.swing.JLabel lblpromptItem;
    // End of variables declaration//GEN-END:variables

    public void initCategories() {
        waiterUI.getController();
        ArrayList<String> temp = waiterUI.getMenuCategories();
        cbCategory.removeAllItems();
        for(int i =0; i <temp.size();i++){
            cbCategory.addItem(temp.get(i));
        }
    }
    //this populates the items combobox with items from the chosen category
    public void initItems(){
        if(cbCategory.getSelectedItem()!=null){
            String currentCategory = cbCategory.getSelectedItem().toString();
            //System.out.println(currentCategory);
            ArrayList<MenuItem> tempItems = waiterUI.getItemsOfCategory(currentCategory);
            cbItem.removeAllItems();
            //now the list needs to be populated
            for(int i =0; i<tempItems.size();i++){
                cbItem.addItem(tempItems.get(i));
            }
        }
    }
    
    public void initQuantities(){
        cbQuantity.removeAllItems();
        for(int i =1;i<11;i++){
            cbQuantity.addItem(i);
        }
    }
    
    public void updateSubtotal(){
        if(cbItem.getSelectedItem()!=null){
            MenuItem item =(MenuItem)cbItem.getSelectedItem();
            double price = item.getMenuItemPrice();
            //System.out.println(cbQuantity.getSelectedItem().getClass());
            //System.out.println(cbQuantity.getSelectedIndex()+1);
            int quantity = cbQuantity.getSelectedIndex()+1;
            double total = price*quantity;
            lblSubtotalValue.setText(Double.toString(total));
        }
        
    }
}
